### ISSUE TITLE
How to check on the status of an application 

### ISSUE THREAD

**Issue by hareemm** [USAJOBS/Help#106]
Link reads "How to check the status of an application", actual title reads "How to check on the status of an application". Needs to match

"Referred" font size is 19px instead of 17px, should be 17px.

Explore possibility of inserting bullets to create a level of hierarchy within the information presented.

Under "Related Articles" - remove "How to check on the status of an application".

<img width="352" alt="screen shot 2016-08-11 at 10 29 03 am" src="https://cloud.githubusercontent.com/assets/17989522/17591981/78b20426-5fae-11e6-8f3b-eecc3d3766bd.png">

**Comment by dalenard21** [comment]
@hareemm 

I fixed the font size for Referred.  Good catch.

Also, in UAT the styles are not rendering properly.  I think it's because they haven't applied the full design system to UAT, so the indentation of the numbered and bulleted lists is not working properly.  Is that correct @humancompanion ?

Regarding hierarchy, are you talking about the status types and descriptions? I agree it's a bit hard to distinguish.  The status category is an H3 and the sub-categories are just bolded.  Don't think doing an H4 will help much. But,  I'm also hesitant to use bullets here - list with lengthy descriptions. @humancompanion any thoughts? 

Other actions for @humancompanion 

1. Can you update the link on the How To landing page to read "How to check on the status of an application"?
2. Also, the related articles issue - I think this is something we can't fix right now?
