### ISSUE TITLE
Need content on "upload docs over 3 MB"

### ISSUE THREAD

**Issue by PeterToohey** [USAJOBS/Help#132]
According to the helpdesk, a common complaint is that folks are unable to upload documents over 3MB.  

We inform users that 3MB is too large on this page (http://usajobs.github.io/Help/how-to/account/documents/) but do not tell them what to do if it is too large.

We need content for this issue.  Peter is tracking down the QD for this issue now.

**Comment by dalenard21** [comment]
@PeterToohey 

When does this need to get updated?  Which release...5.8?

**Comment by PeterToohey** [comment]
5.9 release....August 30th?


_______________________________
Peter Toohey
Excella Consulting / Senior Consultant
617.584.5420 / peter.toohey@excella.com
@excellaco / excella.com

________________________________

**Comment by dalenard21** [comment]
sounds good.  just let me know when you get the info from the help desk.

**Comment by dalenard21** [comment]
Content from the help desk:

Issue #6: How do I upload a document when it is more than 3MB?
 
We use…
 
Uploaded documents must be less than 3 MB (3,072 KB) and in one of the following formats: GIF, JPG, JPEG, PNG, RTF, PDF, or Word (DOC or DOCX).
  
If files are larger than 3 MB, here are some suggestions:
 
·     Take your documents to an office supply store (i.e. Staples, FedEx Office/Kinkos, etc.) that can change the resolution (shrink) documents for you and save them to a disk or flash drive.  Be sure to inform the office tech the document cannot exceed 3 MB (3,072 KB).
·     If you have a scanner and the capability to shrink the document size, you can change the size and scan them in yourself.
 
NOTE: Transcripts sent directly from an educational institution tend to have a security block (viewed as a virus) that prevents the document from being uploaded as well as being a very large file.  You will need to print your transcript and then scan it in order to upload.

**Comment by humancompanion** [comment]
For this issue, the real fix is for us to support file sharing services like Dropbox and Google Docs. I’m hoping that is something we can do in App Guide v2, but it is potentially a long way off. But the transcript issue they mention isn’t easily solved. Then again, hard to say how common a security block in a PDF actually is.

I would go with what Adobe suggests:
https://acrobatusers.com/tutorials/reducing-file-size

Then I would briefly get into the fact that some image types are large than others (jpeg is the largest on down to png which generally the smallest) and that images can be compressed with a variety of tools. 

Converting a PDF to images is also possible, but users can only upload one image as their document so they’d have to join the images together which adds some complication.

**Comment by dalenard21** [comment]
Okay, here's what I have.  I think we just link to Adobe's article instead of repeating it...they have all the details.  Then, offer some of the suggestions the help desk sent.

If your document is larger than 3 MB, here are some suggestions:

•	Read Adobe’s tutorial on[ how to reduce PDF file size](https://acrobatusers.com/tutorials/reducing-file-size).
•	Print your document, scan it (if you have a personal scanner) and save it at a smaller size. 
•	Use a smaller image format.  Different image formats have varying sizes – JPEG files typically are the largest and PNG files are the smallest.
•	Take your document to an office supply store (i.e. Staples, FedEx Office/Kinkos) and ask them to shrink the document size for you and save it to a disk or flash drive. Make sure you tell the office tech the document can’t exceed 3MB (3,072 KB).

**Transcripts**
Sometimes transcripts from an educational institution will have a security block that is flagged as a virus and makes the file very large—this prevents the file from being uploaded. If that happens, you need to print your transcript and scan it in to upload.

**Comment by dalenard21** [comment]
Added the 'how to' content to the How to upload documents content.
/how-to/account/documents/upload.md

Also added a link to the how do I upload documents over 3mb on the "How to manage documents" page.

/how-to/account/documents/index.md

@humancompanion Content ready for 5.9.  Issue closed.
