### ISSUE TITLE
Remove/Rewrite RSS Feed Article on Help Center

### ISSUE THREAD

**Issue by KatMullens-work** [USAJOBS/Help#286]
RSS feed support no longer exists but we refer to it in Help Center: https://www.usajobs.gov/Help/how-to/search/results/feed/

Per Mr. Still: Yes we did retire the RSS feed last year so that page should be removed or re-written to refer users to the API at https://developer.usajobs.gov/

**Comment by dalenard21** [comment]
@humancompanion do you want to refer to the API or just remove it?

**Comment by humancompanion** [comment]
This page isn't in the Help Center distribution at all. I'll ping @kikaider05 about this page. I do see it in production but, it should not be there.

**Comment by dalenard21** [comment]
@humancompanion did you ever hear anything back about this page?  It's still in production if you go directly to the URL, but it's not in GitHub anymore.  I'd like to close this issue.

**Comment by humancompanion** [comment]
@sabushanab - Saleim: Any idea why this page is still hanging out?

**Comment by dalenard21** [comment]
@sabushanab Hi Saleim,  I'm following up on a bunch of old GitHub issues and this one is still open because the page is still out there in production, even though the file is no longer in the Help Center repo.  Low priority, but if you get a chance, do you know why the page is still out there?  ANd, what do we need to do remove it?  Thanks.
