### ISSUE TITLE
Learn a skill

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#317]
Given that Open Opps cannot yet handle the amount of traffic Core could throw it's way we've decide in this release (Profile) to leave the "Learn a skill" drawer out of the rightrail in Profile.

For the next release I'd like to bring it back but, I doubt Open Opps will have completed their performance improvements. So what I'd like to suggest is that we create a target page for the contents of that draw that would index all of the developmental opportunities that we have gathered thus far (https://airtable.com/tblDabhNXVYfDkUwh/viw5oiIbyJpVN5hg2) onto an index page. We can organize that and edit the list however you both see fit.

Thus the contents of the drawer could be something like "There are many ways to learn a new skill based on where you are in your career and your interests. [Have a look at our list of developmental opportunities]." That last sentence would link to this new page in the Help Center. Open Opps could be listed on that page which would send some traffic there but not as much as it being the only link in the drawer.

This approach will also let us use Google Analytics to measure traffic to the sites in our index (I'll take care of figuring this out in DAP). That may help us determine what could be promoted into the drawer at some point in the future.

Old Trello URL: https://trello.com/c/FgfEil7d/1232-help-center-learn-a-skill

**Comment by dalenard21** [comment]
@kbwagner I'm going through the list of all issues assigned to me in GitHub and this is something Matt talked about a year ago.  I don't think the link to "Learn a new skill" in the USAJOBS right rail is there yet, is it? I don't see if when I sign in, but that might be because I'm not a current Fed.

Know anything about this?  And, I wonder if it's something to pursue? I haven't looked at the Airtable to see what he means by other development opportunities.  I can close this if it's not something on anyone's radar.

**Comment by Piglady64** [comment]
@dalenard21 "learn a new skill" is in the right rail on USAJOBS in production.
![image](https://user-images.githubusercontent.com/15252970/63962034-16d15700-ca60-11e9-8a28-a31868a4f504.png)

![image](https://user-images.githubusercontent.com/15252970/63962054-29e42700-ca60-11e9-9a5a-ccbf0b8d778b.png)

**Comment by dalenard21** [comment]
Great. I guess because you're a federal employee it shows up for you. I'll close this issue now.
