### ISSUE TITLE
Improve reinstatement page

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#320]
This is the page we link to from Federal service for reinstatement:

https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/federal-employees/reinstatement/

It pretty much repeats what we now have inline in the Help section on that page. Can we improve it so it offers more value? Perhaps how to determine if you have reinstatement? Is this one of the pages Ky revised that we never deployed? Perhaps we could pick that design up again? (I'll have to dig around for his mocks; we may in fact have an issue for this already)

**Comment by dalenard21** [comment]
Here is the latest info from Michelle G. on career-conditional vs. career employees and reinstatement.  

Michelle also answered these questions:

1.	Do you still have to be a former COMPETITIVE service employee or can any former federal employee apply under reinstatement?  

Michelle's answer: "A person who previously held a career or career-conditional appointment (or equivalent) may be appointed by reinstatement."

2.	I know you no longer have to work 3 continuous years, but do you have to work at least 1 year? Or, can ANY former employee apply under reinstatement. For example, can they apply under reinstatement if they only worked for 3 months? 

Michelle's answer: "In order to apply under reinstatement, you must have a total of 3 years of creditable service.  If a person only has 3 months of creditable service, they are not eligible to apply under reinstatement.  *you are mixing 2 different concepts* "

3.	Is it lifetime reinstatement for everyone? 

Michelle's answer: "A preference eligible or a person who has completed 3 years of creditable service has no limit on their reinstatement eligibility. Or are there time limits for when you can use it? A person who does not have 3 total years of creditable service to obtain “status”, has 3 years to return to the competitive service under reinstatement."

4.	Do you still have to leave the job voluntarily?  

Michelle's answer: "Not sure what you mean. Does it apply to someone who’s been ‘RIF’d’? The priority placement procedures at 5CFR 330 for RPL, CTAP, ICATAP are used  under RIF, not reinstatement."

**Comment by dalenard21** [comment]
Michelle also sent me this PDF that explains the 'creditable service' for career and career conditional employees. It talks briefly about reinstatement. 

https://chcoc.gov/sites/default/files/QAs%20Career%20and%20Career-Conditional%20Employment--Creditable%20Service.pdf

I updated my content and sent her another version to review.

**Comment by dalenard21** [comment]
Sent another follow up email to see if Michelle has had a chance to review the updated content.  Moving this to 'review'

**Comment by humancompanion** [comment]
MichelleG asked that we send this along again.

**Comment by humancompanion** [comment]
Debbie to meet with MichelleG but we're going to put this in and send it out with the January release.
