### ISSUE TITLE
Transcripts Content to be updated in Help Center

### ISSUE THREAD

**Issue by KatMullens-work** [USAJOBS/Help#330]
Please update the transcripts help article to include that we cannot upload encrypted files (and how to unencrypt them if possible.).

**Comment by dalenard21** [comment]
Updated the following:

https://federalist-proxy.app.cloud.gov/site/usajobs/help/how-to/account/documents/upload/

Added message about no encrypted files to "How to upload documents", since it applies to all documents and not just transcripts.  Also added a link to the transcript help article.

https://federalist-proxy.app.cloud.gov/site/usajobs/help/working-in-government/unique-hiring-paths/students/transcripts/

Added link to the transcript help article pointing to how to upload documents.

Changes will go into production the next time there's a Help Center build.

**Comment by KatMullens-work** [comment]
Hi Deb:

Thanks this looks great!

Any chance we could add content about how to unencrypt a document?

Thanks,
kat


-----------
Kathlene “Kat” Mullens, MLHR, SPHR, BSBA
USAJOBS Engagement Specialist and Social Media

U.S. Office of Personnel Management
Mobile:  202.491.6958
Kathlene.Mullens@OPM.gov

**Comment by dalenard21** [comment]
These updates are in production.

https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/students/transcripts/

https://www.usajobs.gov/Help/how-to/account/documents/upload/

The updates do not include steps to decrypt a file.  There are various ways to decrypt a file - it depends on the type of document, the type of software and the type of computer you have and I don't think we should endorse a particular way to do it. 

Issue closed.

**Comment by KatMullens-work** [comment]
Okay thank you!
