### ISSUE TITLE
Add item about "area of consideration"

### ISSUE THREAD

**Issue by KatMullens-work** [USAJOBS/Help#331]
Most people don't understand what this is. Could we please add an item to the Help Center about it so we could educate on it via social media, etc.? Thank you!

**Comment by humancompanion** [comment]
I'm not sure I understand what it is and how it is different from who is eligible to apply. Can you elaborate on what you want us to cover? Also, where is area of consideration defined in the DEO Handbook?

My rough understanding is that an agency can further limit who they will consider within the eligibility defined in the This job is open to section of the JOA. The only definition I've seen is from the MS 620 Direct Hire Merit Selection and Promotion here: 

https://files.peacecorps.gov/documents/MS-620-Policy.pdf

> Area of Consideration means the geographical or organizational area in which the
> Agency makes a search for eligible candidates in filling a specific vacancy or vacancies
> through competitive procedures. 

Geography I get. Organizational area seems a bit more nebulous. In practice, it seems like a way for agencies to further reduce the potential pool of applicants in order to keep a lid on the number of applicants. What is your take?

**Comment by Piglady64** [comment]
The Organizational area would be more like "Current HHS employees" because I need someone with a good understanding of the mission without having to get them up to speed. I have also seen this when the agency already has someone in mind and really wants to promote someone but their current position is only classified up to a certain grade. They have to create a new position with the higher grade and the person will have to apply for the position. This practice will eliminate people from the outside from applying.

**Comment by KatMullens-work** [comment]
I think we really just need to explain what area of consideration is and that's it's not just geography or citizenship and have that available in the Help Center.
