### ISSUE TITLE
Article Addressing if Postal Employees are Federal Employees

### ISSUE THREAD

**Issue by KatMullens-work** [USAJOBS/Help#341]

**Comment by humancompanion** [comment]
Postal employees are federal employees. I understand there are some myths around this (http://postalnews.com/blog/2015/05/09/postal-myths-2-the-usps-is-not-a-government-agency/). However, I'm not sure what this article should say. We're not the source of truth here in that we're not the USPS and we, USAJOBS, are not the arbitrator of who and who is not a federal employee. While that might be OPM I would think opm.gov would have that answer. 

So, what's the ask here @KatMullens-work? Does this question come up because folks want to know why postal jobs are not on our site? Because I would like to write a broader article about that with pointers to where other folks could find those other jobs/sites.

**Comment by KatMullens-work** [comment]
Hi Matt:

I think an article providing some information to help Postal employees know where they fall in the eligibility buckets would be useful. As there are not any good articles I’ve found to point folks to with a “.gov” ending, it would be nice if we had one as those are the questions I sometimes get “am I federal employee or not?” and the answer is “sorta”. It’s a very confusing issue we could provide a little clarity to, especially since there are USPS jobs on our site.

Thanks,
kat

**Comment by KatMullens-work** [comment]
Hi Matt: Any chance we could bubble this back up? John Still has a great item that used to be on our site about it that he could share. Thanks!

**Comment by dalenard21** [comment]
@KatMullens-work feel free to upload the old content in this issue and we can review/work on this once we get through State. Thanks.

**Comment by KatMullens-work** [comment]
[EI-29 Appointment of Postal Employees..pdf](https://github.com/USAJOBS/Help/files/3038968/EI-29.Appointment.of.Postal.Employees.pdf)
Here's the document :)
