### ISSUE TITLE
Security Clearance Updates

### ISSUE THREAD

**Issue by danthibodeau** [USAJOBS/Help#350]
https://www.usajobs.gov/Help/how-to/search/filters/security-clearance/ needs to be updated with the new security clearance list

**Comment by dalenard21** [comment]
@danthibodeau what are the new security clearance lists/levels?

**Comment by danthibodeau** [comment]
Security clearance
Select all  Help

 Not Required (2488)

 Confidential (128)

 Secret (2785)

 Top secret (280)

 Sensitive Compartmented Information (377)

 Q Access Authorization (90)

 L Access Authorization (11)

 Other (3216)

**Comment by danthibodeau** [comment]
minus the numbers of course, just copied that from the search page

**Comment by danthibodeau** [comment]
Looks like public trust may be listed on other pages too, at least on https://www.usajobs.gov/Help/faq/job-announcement/security-clearances/

**Comment by dalenard21** [comment]
@danthibodeau but is Public Trust gone or is it just removed from "Security Clearance" filters because it's not really a security clearance...as the definition says on this page: https://www.usajobs.gov/Help/faq/job-announcement/security-clearances/

I did update the security clearance options on the how to search by security clearance page.  

@humancompanion this page is updated: https://github.com/USAJOBS/Help/blob/master/how-to/search/filters/security-clearance.md

It's ready to go out with the next Help Center release.

**Comment by danthibodeau** [comment]
Good catch Debbie! You're right, it's just not a security clearance.

**Comment by dalenard21** [comment]
Here's the updated how to filter by security clearance page 

https://federalist-proxy.app.cloud.gov/site/usajobs/help/how-to/search/filters/security-clearance/

**Comment by dalenard21** [comment]
The security clearance filter page has been updated with new values.

https://www.usajobs.gov/Help/how-to/search/filters/security-clearance/

Issue closed.
