### ISSUE TITLE
Update Individuals with a disability page - Tips for applying no longer accurate

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#355]
The tips for applying drawer has this content:

> Select the "Schedule A Disabled" option in your USAJOBS account profile on the "Special Hiring Options" page – this helps your resume be searchable by agencies that want to find people who may be eligible to apply under "Schedule A".

That location in the profile is no longer accurate. We should probably just tell them to select the appropriate hiring path though I'm curious to know if anything in resume mining has been mapped to the hiring paths.

**Comment by dalenard21** [comment]
@humancompanion what about this?

Julie looked at the resume mining tool and it looks like they do have a filter for "Individuals with a schedule A qualifying disability". She's checking with Brody to see if that actually flags the hiring path selection.  If it does, this is what I propose:

If you're eligible for Schedule A, go to your profile and select the **Individuals with disabilities** hiring path and make your resume searchable. With this hiring path and a searchable resume, agencies who are looking for people eligible under Schedule A, may be able to find you. 

It's a bit of a mouthful, so open to feedback.

**Comment by humancompanion** [comment]
@dalenard21 - Looks good to me.

**Comment by Piglady64** [comment]
@dalenard21 @humancompanion Apparently they haven't updated ATP to recognize the hiring paths. See discussion with Brody below:

When an ATP user uses the "Individual with a Schedule A qualifying disability" filter do they get resumes for anyone who has chosen the "Individual with a disability" hiring path?

Brody Dittemore [10:33 AM]
Generally, the filter has to be combined with a keyword query. But that's an aside here.
ATP is still not coded to support hiring paths. We are pulling the older profile data
I am blanking on what we used to call it. Eligibilities?

Lauren Foreman [11:08 AM]
This information is pilled from the older profile information. Not from hiring paths.
Pulled*

Julie Jackson [11:55 AM]
so we aren't pulling anything from the new users that are using the hiring paths
Didn't we convert everyone to the hiring paths in Core? If so, when the ATP user uses the filters what are they getting for results?

Lauren Foreman [12:09 PM]
@brody can answer those technical questions. But I asked when we would update hiring paths in ATP. I know those tickets are in the backlog.

Brody Dittemore [1:00 PM]
ATP info for eligibilities isn't being updated and mapped to hiring paths. Not sure when we'll get to it, but there is a larger movement to endorse hiring paths between ATP abs TASs

Julie Jackson [1:02 PM]
So the filters are pretty useless is ATP right now then since USAJOBS users are selecting hring paths and ATP hasn't mapped them?

Julie Jackson [1:03 PM]
If I am looking for a quick hire using a veteran or schedule A hiring authority Resume Mining won't help me do that quickly. I will havet to look through each person to see if they meet eligibliity?

Lauren Foreman [2:56 PM]
Hmmm never thought about that, but Julie brings up a great point. Are the hiring paths in ATP accurate
How do they find for example Veterans if we are pulling old data.

Thread:  
So the filters are pretty useless is ATP right now then since USAJOBS users are selecting hring paths and ATP hasn't mapped them?
2 replies

Brody Dittemore   [2 hours ago]
Based upon seekers update cycles, I don't think I'd  call this useless. Not updated, but not useless or even of minimal use

Julie Jackson   [2 hours ago]
How do they find people who are eligible for hiring authorities if the filters aren't mapped to the hiring paths

**Comment by dalenard21** [comment]
@humancompanion @Piglady64 

I updated the page to say the following:

If you're eligible for Schedule A, go to your profile and select the **Individuals with disabilities** hiring path and make your resume searchable. If your resume is searchable, agencies who are looking for people eligible under Schedule A, may be able to find you.

Let me know if you have any edits, otherwise, it's good to go for the next release.

**Comment by Piglady64** [comment]
Sounds good

Julie Jackson
Usability Test Lead
USAJOBS

P: 202-606-5230 | M: 202-718-7608
Julie.Jackson@opm.gov<mailto:Julie.Jackson@opm.gov> | www.opm.gov/HRS<http://www.opm.gov/HRS>
[USAJOBS]<https://www.usajobs.gov/>
[usajobs-facebook-s]<https://www.facebook.com/USAJOBS>[usajobs-twitter-s]<https://twitter.com/usajobs> [usajobs-linkedin-s] <https://www.linkedin.com/company/usajobs>  [usajobs-youtube-s] <https://www.youtube.com/c/usajobs>

**Comment by dalenard21** [comment]
This has been updated in production.

 https://www.usajobs.gov/Help/working-in-government/unique-hiring-paths/individuals-with-disabilities/

Issue closed.

**Comment by humancompanion** [comment]
@dalenard21 - When you're editing an HTML file you cannot use markdown:

```
If you're eligible for Schedule A, go to your profile and select the **Individuals with disabilities**
```

You have to use HTML. For example:

```
If you're eligible for Schedule A, go to your profile and select the <strong>Individuals with disabilities</strong>
```

You can tell which you are editing by the file extension (.html for HTML and .md for markdown).

**Comment by dalenard21** [comment]
Oops.  I missed that.

**Comment by dalenard21** [comment]
@humancompanion I fixed it. thanks for the catch. I'm going to close the issue again, because it will just go out with the next release.
