### ISSUE TITLE
How-to: Create content for how-to/account/documents

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#45]
We need to create content in how-to/account/documents (currently just a placeholder page) that details the new Documents section of Account.

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey 

I created content for how to > documents.  I must say it's rather light.  There's more content for resumes, but most of it links out to other help content we have.  There's not much to the "other documents" section.  I don't think we need to say "Click Edit to edit a document", "Click Delete to delete a document", etc.  But, let me know if you feel different.

Also, I added links to "What types of documents might I need" and "Where can I find documents".  But, honestly, I think those links should be ON the other documents page in the account rather than making the user go two clicks in to find it.  Thoughts?

Please review and let me know if you have feedback.
[How to manage documents-profile-dashboard_20160512.docx](https://github.com/USAJOBS/Help/files/262097/How.to.manage.documents-profile-dashboard_20160512.docx)

**Comment by humancompanion** [comment]
I'll take adding this one.

**Comment by PeterToohey** [comment]
@dalenard21 Just emailed you feedback.  Looks pretty good.  GitHub was not allowing me to attach the doc.
