### ISSUE TITLE
Internal Links to old Resource Center (Monday, May 9th)

### ISSUE THREAD

**Issue by dgarber** [USAJOBS/Help#60]
Yesterday we had 7,106 hits to old Resource Center. One week ago it was 47K, so we still have ~15% of traffic going to the old site. 4,682 of these hits (or ~68% of this traffic) is originating within USAJOBS. Attached is a report that includes the referral path and destination. Good news is there are several quick fixes in the account creation process. Bad news is there are a lot of referrals from JOA pages, which likely means links are embedded in agency templates.

[Analytics OPM Agency Profile Pages 20160509-20160509.pdf](https://github.com/USAJOBS/Help/files/257448/Analytics.OPM.Agency.Profile.Pages.20160509-20160509.pdf)

I was able to find the top referrer on the confirm your account, but couldn't find 3 or 4. Could these be part of the error validation text?

![image](https://cloud.githubusercontent.com/assets/2085500/15148919/95b814f0-1695-11e6-84fa-5c19f95f3a7e.png)

**Comment by humancompanion** [comment]
@dgarber - Thanks for the report. Unfortunately, the first column is really slim so I cannot read the URLs. Can you share that customized report via DAP with me?

I'm not surprised that creating a new account has links to Resource Center. That entire page has been orphaned.

**Comment by dgarber** [comment]
@humancompanion try the 'Go to this report' link in the top right of the report. Below is the report as an xlsx just in case.

[Analytics OPM Agency Profile Pages 20160509-20160509.xlsx](https://github.com/USAJOBS/Help/files/258318/Analytics.OPM.Agency.Profile.Pages.20160509-20160509.xlsx)

**Comment by humancompanion** [comment]
Okay, I had a look and these are, for the most part, stemming from pages that we haven't touched yet. But we did miss a few that will required TFS tickets.

#### Pages not yet updated with the design system

* Account confirmation 
  * login.usajobs.gov/account/confirm
  * my.usajobs.gov/Account/CreateAccountConfirmed/

In fact, we haven't updated anything living at login.usajobs.gov. I believe updates to those pages are forthcoming.

#### Links we missed

* Hiring Eligibility (usajobs.gov/Applicant/Profile/HiringEligibilityData/)
* Support - Thank You (my.usajobs.gov/Support/ThankYou/)

@dgarber - I talked to Saleim about flushing the Akami cache after a release for Help Center but, I think we might want to consider doing that system wide when we make broad changes like this. Because I'm still today (5/13) seeing people hit help.usajobs.gov from pages and links that I know have been updated. Is it possible folks just have these pages cached still?
