### ISSUE TITLE
Documents > Resume - Add new resume info to How to create a resume

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/Help#82]
RPO sent the attached content for writing a federal resume. This content is intended to replace the sample resume currently on the site. 
[Resume.handout.6_24_2016.docx](https://github.com/USAJOBS/Help/files/337202/Resume.handout.6_24_2016.docx)

**Comment by humancompanion** [comment]
@dalenard21 - I've added this document but, you should have a look at it. I suspect applicants would be better served by this content if we got it out of the PDF/Word document and into the pages we already have for resume writing. Thoughts?

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey @Piglady64 

Agreed.  The pdf is certainly helpful as a handout, but the content included in the pdf is different than what we currently have on the site and we should get them in sync.

Here's our current page on What to include in a resume https://www.usajobs.gov/Help/faq/application/documents/resume/what-to-include/

1. The biggest difference here is that our current help center page talks about Keywords.  The sample pdf doesn't talk about keywords at all.  Is that still something they want to push/highlight?
2. The "sample" we currently have on the site is a real sample resume.  What they provided are tips with a couple of call-outs as examples.  Don't want to get into semantics, but we can't call this new pdf a "sample resume".  

**Suggestion**
We edit our current "what to include in a resume" to include some of the content from their PDF.  I've attached this content and will send via email.  

I did NOT include the part about adding a resume to USAJOBS.  We already have content on that in the help center.  

I did NOT include the "Don't Forget" section.  Again, that's great for a handout, but not needed for online.

I reordered the sections.  I moved the Facts about federal hiring process to the bottom of the page, because it's not the most important thing.  What to include is more important and therefore I put it above.  

I'm open to suggestions on whether we should have the "Before you start" section -- basically tells them to read the announcement and make sure they're eligible before applying.  

Let me know if you have feedback. Once you review I'll pass along to  Tracy for review and then assume it needs to go back to RPO?
[What should I include in my federal resume_2016-07-05_v2.docx](https://github.com/USAJOBS/Help/files/350396/What.should.I.include.in.my.federal.resume_2016-07-05_v2.docx)

**Comment by dalenard21** [comment]
@humancompanion @PeterToohey @Piglady64 

There are a few pages that reference the existing sample resume and will need to be removed and/or replaced with a link to the "What should I include in my resume".  Here are the pages that need to be updated for this issue:

•	Update What should I include in my resume page with the new content.
•	Remove the “Sample Resume (PDF)” and “Sample Resume (Word doc)” links from the How to create a resume page.
•	Add a link to “What should I include in my resume” under additional resources (or can it be in related articles?)
•	Remove “Sample Resume” from How to edit a resume.
•	Edit the additional resource on How to edit a resume to state “what should I include in my resume” (instead of What to include).

I can make these changes once the content is reviewed/approved. If you can think of any other places that need to be updated, let me know.

**Comment by PeterToohey** [comment]
@humancompanion @Piglady64 @dalenard21 

We also need to add a ticket to change the links on App Guide Resume pages.

**Comment by dalenard21** [comment]
Incorporated feedback and sent content to Tracy for review and approval.

**Comment by dalenard21** [comment]
Reviewed by Tracy, made some additional edits to the content based on her feedback.  Content is ready. issue closed.
